name: align_ai
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  camera: ^0.10.5+9
  tflite: ^1.1.2
  tflite_v2: ^1.0.0
  font_awesome_flutter: ^10.7.0
  line_awesome_flutter: ^2.0.0
  raised_buttons: ^0.0.2
  flutter_lints: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
   - assets/posenet_mv1_075_float_from_checkpoints.tflite
   - images/

